//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VVVF_Simulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40000")]
        public int RealTime_VVVF_BuffSize {
            get {
                return ((int)(this["RealTime_VVVF_BuffSize"]));
            }
            set {
                this["RealTime_VVVF_BuffSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RealTime_VVVF_WaveForm_Show {
            get {
                return ((bool)(this["RealTime_VVVF_WaveForm_Show"]));
            }
            set {
                this["RealTime_VVVF_WaveForm_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_VVVF_EditAllow {
            get {
                return ((bool)(this["RealTime_VVVF_EditAllow"]));
            }
            set {
                this["RealTime_VVVF_EditAllow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40000")]
        public int RealTime_Train_BuffSize {
            get {
                return ((int)(this["RealTime_Train_BuffSize"]));
            }
            set {
                this["RealTime_Train_BuffSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_EditAllow {
            get {
                return ((bool)(this["RealTime_Train_EditAllow"]));
            }
            set {
                this["RealTime_Train_EditAllow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_WaveForm_Show {
            get {
                return ((bool)(this["RealTime_Train_WaveForm_Show"]));
            }
            set {
                this["RealTime_Train_WaveForm_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_VVVF_Control_Show {
            get {
                return ((bool)(this["RealTime_VVVF_Control_Show"]));
            }
            set {
                this["RealTime_VVVF_Control_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_Control_Show {
            get {
                return ((bool)(this["RealTime_Train_Control_Show"]));
            }
            set {
                this["RealTime_Train_Control_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealTime_VVVF_Control_Style {
            get {
                return ((int)(this["RealTime_VVVF_Control_Style"]));
            }
            set {
                this["RealTime_VVVF_Control_Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealTime_Train_Control_Style {
            get {
                return ((int)(this["RealTime_Train_Control_Style"]));
            }
            set {
                this["RealTime_Train_Control_Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealTime_VVVF_Control_Language {
            get {
                return ((int)(this["RealTime_VVVF_Control_Language"]));
            }
            set {
                this["RealTime_VVVF_Control_Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealTime_Train_Control_Language {
            get {
                return ((int)(this["RealTime_Train_Control_Language"]));
            }
            set {
                this["RealTime_Train_Control_Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_VVVF_Hexagon_Show {
            get {
                return ((bool)(this["RealTime_VVVF_Hexagon_Show"]));
            }
            set {
                this["RealTime_VVVF_Hexagon_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_Hexagon_Show {
            get {
                return ((bool)(this["RealTime_Train_Hexagon_Show"]));
            }
            set {
                this["RealTime_Train_Hexagon_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealTime_VVVF_Hexagon_Style {
            get {
                return ((int)(this["RealTime_VVVF_Hexagon_Style"]));
            }
            set {
                this["RealTime_VVVF_Hexagon_Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealTime_Train_Hexagon_Style {
            get {
                return ((int)(this["RealTime_Train_Hexagon_Style"]));
            }
            set {
                this["RealTime_Train_Hexagon_Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RealTime_VVVF_Hexagon_ZeroVector {
            get {
                return ((bool)(this["RealTime_VVVF_Hexagon_ZeroVector"]));
            }
            set {
                this["RealTime_VVVF_Hexagon_ZeroVector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RealTime_Train_Hexagon_ZeroVector {
            get {
                return ((bool)(this["RealTime_Train_Hexagon_ZeroVector"]));
            }
            set {
                this["RealTime_Train_Hexagon_ZeroVector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_VVVF_FFT_Show {
            get {
                return ((bool)(this["RealTime_VVVF_FFT_Show"]));
            }
            set {
                this["RealTime_VVVF_FFT_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_FFT_Show {
            get {
                return ((bool)(this["RealTime_Train_FFT_Show"]));
            }
            set {
                this["RealTime_Train_FFT_Show"] = value;
            }
        }
    }
}
